### ISSUE TITLE
indexのmembersコンポーネントを追加

### ISSUE THREAD

**Issue by east9698** [toyolabio/www.toyolab.io#7]
indexでの運営メンバー紹介的なイメージ

**Comment by east9698** [comment]
代表メンバーだけ表示して、もっと見るボタンを置いて、membersページに飛ばす

**Comment by y-koki1023** [comment]
代表メンバーって誰？

**Comment by y-koki1023** [comment]
Ant designのCardを使って実装
一行に3 人のユーザーを表示する。
ユーザー情報のボトムにはGithubのアイコンとか置く
